services:
  short-url:
    container_name: short-url
    build: .
    restart: always
    ports: 
      - "8080:3000" 
    networks:
      - net
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb-container
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=passnojsmgdb
    networks:
      net:
        ipv4_address: 192.168.16.2
    volumes:
      - vol:/data/db

networks:
  net:  
    driver: bridge
    ipam: 
      driver: default
      config:
        - subnet: 192.168.16.0/24  

volumes:
  vol: