services:
  short-url:
    container_name: short-url
    build: .
    restart: always
    ports: 
      - "8080:3000" 
    environment:
      - PORT=3000
      - BASE_URL=http://localhost:8080
      - MONGO_URI=mongodb://root:passnojsmgdb@mongodb-container:27017/?authsource=admin
    networks:
      - net
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb-container
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=passnojsmgdb
    networks:
      - net
    volumes:
      - vol:/data/db

networks:
  net:  

volumes:
  vol: